# Generated by Django 5.2.5 on 2025-10-05 04:12

import enrollments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(editable=False, help_text='Se genera automáticamente al crear la inscripción.', max_length=6, validators=[enrollments.models.validate_semester])),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('activa', 'Activa'), ('regular', 'Regular'), ('aprobada', 'Aprobada'), ('reprobada', 'Reprobada'), ('ausente', 'Ausente')], default='activa', max_length=10)),
            ],
            options={
                'verbose_name': 'Inscripción',
                'verbose_name_plural': 'Inscripciones',
                'ordering': ['-enrolled_at', 'student__surname', 'subject__name'],
            },
        ),
    ]
