# Generated by Django 5.2.5 on 2025-10-09 00:12

import django.db.models.deletion
import enrollments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrollments", "0002_initial"),
        ("students", "0003_alter_student_career"),
        ("subjects", "0002_subject_teacher_alter_subject_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="enrolled_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora en que se realizó la inscripción.",
                verbose_name="Fecha de inscripción",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="semester",
            field=models.CharField(
                editable=False,
                help_text="Se genera automáticamente al crear la inscripción.",
                max_length=6,
                validators=[enrollments.models.validate_semester],
                verbose_name="Semestre",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="status",
            field=models.CharField(
                choices=[
                    ("activa", "Activa"),
                    ("regular", "Regular"),
                    ("aprobada", "Aprobada"),
                    ("reprobada", "Reprobada"),
                    ("ausente", "Ausente"),
                ],
                default="activa",
                help_text="Estado actual de la inscripción.",
                max_length=10,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="student",
            field=models.ForeignKey(
                help_text="Estudiante que realiza la inscripción.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="students.student",
                verbose_name="Inscripción",
            ),
        ),
        migrations.AlterField(
            model_name="enrollment",
            name="subject",
            field=models.ForeignKey(
                help_text="Materia a la que se inscribe el estudiante.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="enrollments",
                to="subjects.subject",
                verbose_name="Materia",
            ),
        ),
    ]
