# Generated by Django 5.2.5 on 2025-11-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_alter_enrollment_enrolled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('activa', 'Activa'), ('regular', 'Regular'), ('aprobada', 'Aprobada'), ('reprobada', 'Reprobada'), ('ausente', 'Ausente'), ('baja', 'Baja')], default='activa', help_text='Estado actual de la inscripción.', max_length=10, verbose_name='Estado'),
        ),
    ]
