# Generated by Django 5.2.5 on 2025-10-07 03:15

import users.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.managers.CustomUserManager()),
            ],
        ),
    ]
