# Generated by Django 5.2.5 on 2025-08-31 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha en que el usuario se unió al sistema', verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dni',
            field=models.CharField(help_text='Documento Nacional de Identidad (único)', max_length=10, unique=True, verbose_name='DNI'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Correo electrónico (único)', max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='force_password_change',
            field=models.BooleanField(default=False, help_text='Indica si el usuario debe cambiar su contraseña en el próximo inicio de sesión', verbose_name='Forzar cambio de contraseña'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indica si el usuario está activo', verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('student', 'Student')], help_text='Rol del usuario en el sistema', max_length=10, verbose_name='Rol'),
        ),
    ]
