# Generated by Django 5.2.5 on 2025-10-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "Administrador"),
                    ("STUDENT", "Alumno"),
                    ("TEACHER", "Profesor"),
                ],
                default="STUDENT",
                help_text="Rol del usuario en el sistema",
                max_length=10,
                verbose_name="Rol",
            ),
        ),
    ]
