# Generated by Django 5.2.5 on 2025-11-11 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('STUDENT', 'Alumno'), ('TEACHER', 'Profesor')], help_text='Rol del usuario en el sistema', max_length=10, verbose_name='Rol'),
        ),
    ]
