# Generated by Django 5.2.5 on 2025-11-13 02:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la persona', max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(help_text='Apellido de la persona', max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad (único)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'DNI inválido. Debe tener 7 u 8 dígitos.')], verbose_name='DNI')),
                ('address', models.CharField(blank=True, help_text='Domicilio', max_length=200, null=True, verbose_name='Domicilio')),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento (YYYY/MM/DD)', null=True, verbose_name='Nacimiento')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono (opcional)', max_length=20, null=True, verbose_name='Teléfono')),
                ('academic_degree', models.CharField(choices=[('GRADUATE', 'Licenciado'), ('ENGINEER', 'Ingeniero'), ('MASTER', 'Magíster'), ('DOCTOR', 'Doctor'), ('TEACHER', 'Profesor')], default='TEACHER', help_text='Título profesional del docente.', max_length=10, verbose_name='Título académico')),
                ('hire_date', models.DateField(help_text='Fecha de contratación del docente.', verbose_name='Fecha de contratación')),
                ('user', models.OneToOneField(help_text='Usuario del docente.', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Profesor',
                'verbose_name_plural': 'Profesores',
                'ordering': ['-hire_date'],
            },
        ),
    ]
