# Generated by Django 5.2.5 on 2025-11-13 03:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_date_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la persona', max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(help_text='Apellido de la persona', max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad (único)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'DNI inválido. Debe tener 7 u 8 dígitos.')], verbose_name='DNI')),
                ('address', models.CharField(blank=True, help_text='Domicilio', max_length=200, null=True, verbose_name='Domicilio')),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento (YYYY/MM/DD)', null=True, verbose_name='Nacimiento')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono (opcional)', max_length=20, null=True, verbose_name='Teléfono')),
                ('department', models.CharField(blank=True, help_text='Departamento del administrador', null=True, verbose_name='Departamento')),
                ('hire_date', models.DateField(help_text='Fecha de incorporación del administrador', verbose_name='Fecha de incorporación')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si el administrador está activo', verbose_name='Activo')),
                ('user', models.OneToOneField(help_text='Usuario asociado a este administrador', on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'ordering': ['-hire_date'],
                'indexes': [models.Index(fields=['is_active'], name='admin_is_active_idx'), models.Index(fields=['department'], name='admin_department_idx')],
            },
        ),
    ]
