# Generated by Django 5.2.5 on 2025-11-28 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_teacher_remove_admin_admin_is_active_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono (opcional)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 8 y 20 caracteres: números, espacios, guiones o paréntesis.', regex='^[\\d\\+\\s()-]{8,20}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, help_text='Número de teléfono (opcional)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe contener entre 8 y 20 caracteres: números, espacios, guiones o paréntesis.', regex='^[\\d\\+\\s()-]{8,20}$')], verbose_name='Teléfono'),
        ),
    ]
