# Generated by Django 5.2.5 on 2025-10-05 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese un nombre único para la carrera.', max_length=100, unique=True, verbose_name='Nombre de la carrera')),
                ('description', models.TextField(blank=True, help_text='Opcional: agrege una breve descripcion de la carrera', null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha en que se creó la carrera.', verbose_name='Fecha de creación')),
                ('is_active', models.BooleanField(default=True, help_text='Indica si la carrera está activa.', verbose_name='Activo')),
                ('subjects', models.ManyToManyField(related_name='careers', to='subjects.subject', verbose_name='Materias')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
