# Generated by Django 5.2.5 on 2025-11-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='career',
            name='description',
            field=models.TextField(blank=True, help_text='Opcional: agregue una breve descripción de la carrera', null=True, verbose_name='Descripción'),
        ),
    ]
