# Generated by Django 5.2.5 on 2025-10-05 04:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la persona', max_length=100, verbose_name='Nombre')),
                ('surname', models.CharField(help_text='Apellido de la persona', max_length=100, verbose_name='Apellido')),
                ('dni', models.CharField(help_text='Documento Nacional de Identidad (único)', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^\\d{7,8}$', 'DNI inválido. Debe tener 7 u 8 dígitos.')], verbose_name='DNI')),
                ('address', models.CharField(blank=True, help_text='Domicilio', max_length=200, null=True, verbose_name='Domicilio')),
                ('birth_date', models.DateField(blank=True, help_text='Fecha de nacimiento (YYYY/MM/DD)', null=True, verbose_name='Nacimiento')),
                ('phone', models.CharField(blank=True, help_text='Número de teléfono (opcional)', max_length=20, null=True, verbose_name='Teléfono')),
                ('career', models.ForeignKey(help_text='Carrera del estudiante', on_delete=django.db.models.deletion.PROTECT, to='careers.career', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
            },
        ),
    ]
