# Generated by Django 5.2.5 on 2025-10-07 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("careers", "0001_initial"),
        ("students", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="career",
            field=models.ForeignKey(
                help_text="Carrera del estudiante",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="students",
                to="careers.career",
                verbose_name="Carrera",
            ),
        ),
    ]
