# Generated by Django 5.2.5 on 2025-11-23 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_career_description'),
        ('students', '0003_alter_student_career'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='career',
            field=models.ForeignKey(blank=True, help_text='Carrera del estudiante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='careers.career', verbose_name='Carrera'),
        ),
    ]
