# Generated by Django 5.2.5 on 2025-10-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="teacher",
            field=models.CharField(
                blank=True,
                help_text="Opcional: ingrese el nombre del profesor de la materia",
                null=True,
                verbose_name="Profesor",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Opcional: agrege una breve descripcion de la materia",
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(
                help_text="Ingrese un nombre único para la materia.",
                max_length=100,
                unique=True,
                verbose_name="Nombre de la materia",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="quota",
            field=models.PositiveIntegerField(
                default=30,
                help_text="Cantidad máxima de estudiantes permitidos en la materia",
                verbose_name="Cupo",
            ),
        ),
    ]
