# Generated by Django 5.2.5 on 2025-11-15 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subjects", "0002_subject_teacher_alter_subject_description_and_more"),
        ("users", "0007_teacher_remove_admin_admin_is_active_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subject",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Opcional: agregue una breve descripción de la materia",
                null=True,
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="teacher",
            field=models.ForeignKey(
                help_text="Docente encargado de la materia",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="subjects",
                to="users.teacher",
                verbose_name="Docente",
            ),
        ),
    ]
